FROM ioft/i386-ubuntu:xenial

# wget, bzip, and git
RUN apt-get update -y && apt-get install git wget bzip2 -y
RUN wget https://storage.googleapis.com/golang/go1.7.3.linux-386.tar.gz

# installing go1.7 for ARM
RUN tar -xf go1.7.3.linux-386.tar.gz
RUN mv go /usr/local

# Configuring go
ENV GOROOT "/usr/local/go"
ENV PATH "$GOPATH/bin:$GOROOT/bin:$PATH"
ENV GOPATH "/opt/go"
RUN mkdir /opt/go
