FROM armv7/armhf-ubuntu

# wget and git
RUN apt-get update -y && apt-get install wget git -y

# installing go1.7 for ARM
RUN wget https://storage.googleapis.com/golang/go1.7.1.linux-armv6l.tar.gz
RUN tar -xf go1.7.1.linux-armv6l.tar.gz
RUN mv go /usr/local

# Configuring go
ENV GOROOT "/usr/local/go"
ENV PATH "$GOPATH/bin:$GOROOT/bin:$PATH"
ENV GOPATH "/opt/go"
RUN mkdir /opt/go
